"""initial

Revision ID: bbd1d9ece2b2
Revises: 
Create Date: 2026-09-28 01:10:41.687175

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbd1d9ece2b2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_norm', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_msg_id', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('bot_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titles')),
    sa.UniqueConstraint('kind', 'bot_id', name='uq_titles_kind_bot_id')
    )
    op.create_index('ix_titles_bot_created_at', 'titles', ['bot_created_at'], unique=False)
    op.create_index('ix_titles_kind_deleted', 'titles', ['kind', 'is_deleted'], unique=False)
    op.create_index('ix_titles_title_norm', 'titles', ['title_norm'], unique=False)
    op.create_index('ix_titles_views', 'titles', ['views'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('app_version', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_favorites_title_id_titles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_favorites_user_title')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('season_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_seasons_title_id_titles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('title_id', 'bot_id', name='uq_seasons_title_bot_id')
    )
    op.create_table('title_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_title_genres_title_id_titles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_genres')),
    sa.UniqueConstraint('title_id', 'slug', name='uq_title_genres_title_slug')
    )
    op.create_index('ix_title_genres_slug', 'title_genres', ['slug'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('episode_title', sa.String(length=200), nullable=True),
    sa.Column('tg_msg_id', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_episodes_season_id_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    sa.UniqueConstraint('season_id', 'bot_id', name='uq_episodes_season_bot_id')
    )
    op.create_table("watch_progress",
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('episode_key', sa.Integer(), nullable=False),
    sa.Column('position_sec', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_watch_progress_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name=op.f('fk_watch_progress_title_id_titles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watch_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_progress')),
    sa.UniqueConstraint('user_id', 'title_id', 'episode_key', name='uq_watch_progress_user_title_episode')
    )
    # ### end Alembic commands ###

    # pg_trgm — faqat PostgreSQL'da (SQLite'da trigram extension yo'q,
    # qidiruv u yerda oddiy `contains` bilan ishlaydi, docs/API.md'ga qarang)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX ix_titles_title_norm_trgm ON titles "
            "USING gin (title_norm gin_trgm_ops)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_titles_title_norm_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_progress')
    op.drop_table('episodes')
    op.drop_index('ix_title_genres_slug', table_name='title_genres')
    op.drop_table('title_genres')
    op.drop_table('seasons')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_titles_views', table_name='titles')
    op.drop_index('ix_titles_title_norm', table_name='titles')
    op.drop_index('ix_titles_kind_deleted', table_name='titles')
    op.drop_index('ix_titles_bot_created_at', table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
